import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"; // Pastikan Navbar diimpor
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Es Teh Mas Toni",
  description: "Generated by create next app ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" type="image/png" href="/assets/images/logo.png" />
        <meta name="theme-color" content="#f8bf55" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Es Teh Mas Toni</title>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ background: "linear-gradient(135deg, #f8f1eb, #f8bf55)" }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
